### ISSUE TITLE
도시간 중복 영역 처리 하기

### ISSUE THREAD

**Issue by G0DCH** [G0DCH/Unity-HexaTile-CasualStrategy#9]
현재 중복 영역이 나중에 설치된 도시의 영역 소유로 됨.
다음과 같은 방식으로 처리되게 변경해야함.

1. 공동 영역으로 둔다.
2. 공동 영역에 건물을 설치한 경우 되도록 먼저 설치한 도시의 소유로 한다.

**Comment by SuperNova911** [comment]
2번의 경우는 사용자의 관점으로 봤을때 직관적이지가 않아보이네요
두 도시 영역의 색상을 구분해주지 않는 이상 그런 규칙이 있다는것을 알아차리기 힘들 듯

**Comment by G0DCH** [comment]
플레이어가 공동영역을 다루는데 신경쓰지 않도록 이렇게 한건데
비 직관적이라면 해결하기 위한 그럼 두가지 방법이 있음

1. 플레이어가 공동영역에 건물을 설치할 때 어떤 도시의 소유로 할 지 결정하게 한다.
2. 말했던 대로 두 도시 영역의 색상을 구분한다.

나는 1이 괜찮아 보이는데 어떰?

**Comment by SuperNova911** [comment]
이런 방법도 있을 거 같음

- A, B 두 도시의 공동 구역에 건물을 설치하면 임의로 아무 도시의 소유로 함
  - A 도시 구역에 건물이 하나 더 설치되면 공동 구역에 있던 건물을 B 도시의 소유로 함
  - B 도시 구역에 설치하는 경우도 위와 마찬가지
  - A, B 공동 구역에 건물이 하나 더 설치되면 A, B 도시 중 남는 도시의 소유로 함

**Comment by G0DCH** [comment]
그 방법이 더 좋은거 같은데 그 방법으로 함.
